CREATE TABLE Livro (
  CodLivro INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Categoria VARCHAR(15) NOT NULL,
  Ano INTEGER UNSIGNED NOT NULL,
  Edicao INTEGER UNSIGNED NOT NULL,
  Titulo VARCHAR(45) NOT NULL,
  numPg INTEGER UNSIGNED NULL,
  Editora VARCHAR(45) NOT NULL,
  Status_2 INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(CodLivro)
);

CREATE TABLE Livraria (
  CodLivraria INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TelFixo INTEGER UNSIGNED NOT NULL,
  RazaoSocial FLOAT NULL,
  Nome VARCHAR(20) NOT NULL,
  Rua VARCHAR(20) NULL,
  Num INTEGER UNSIGNED NULL,
  Cidade VARCHAR(20) NOT NULL,
  UF VARCHAR(3) NULL,
  Fax INTEGER UNSIGNED NULL,
  eMail VARCHAR(20) NULL,
  Site VARCHAR(45) NULL,
  PRIMARY KEY(CodLivraria)
);

CREATE TABLE Amigo (
  CodAmigo INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Pnome VARCHAR(45) NOT NULL,
  Mnome VARCHAR(3) NULL,
  Unome VARCHAR(20) NOT NULL,
  Celular INTEGER UNSIGNED NULL,
  TeleFixo INTEGER UNSIGNED NULL,
  TelTrab INTEGER UNSIGNED NULL,
  eMail VARCHAR(45) NOT NULL,
  PRIMARY KEY(CodAmigo)
);

CREATE TABLE Autor (
  CodAutor INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Pnome VARCHAR(45) NOT NULL,
  Mnome VARCHAR(3) NULL,
  Unome VARCHAR(45) NOT NULL,
  PRIMARY KEY(CodAutor)
);

CREATE TABLE Escreve (
  Autor_CodAutor INTEGER UNSIGNED NOT NULL,
  Livro_CodLivro INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(Autor_CodAutor, Livro_CodLivro),
  FOREIGN KEY(Livro_CodLivro)
    REFERENCES Livro(CodLivro)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Autor_CodAutor)
    REFERENCES Autor(CodAutor)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Compra (
  Livro_CodLivro INTEGER UNSIGNED NOT NULL,
  Livraria_CodLivraria INTEGER UNSIGNED NOT NULL,
  DtCompra DATE NOT NULL,
  Preco FLOAT NULL,
  PRIMARY KEY(Livro_CodLivro, Livraria_CodLivraria),
  FOREIGN KEY(Livro_CodLivro)
    REFERENCES Livro(CodLivro)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Livraria_CodLivraria)
    REFERENCES Livraria(CodLivraria)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Empresta (
  CodEmprest Integer UNSIGNED NOT NULL AUTO_INCREMENT,
  Amigo_CodAmigo INTEGER UNSIGNED NOT NULL,
  Livro_CodLivro INTEGER UNSIGNED NOT NULL,
  DtEmprestimo DATE NOT NULL,
  DtDevolucao DATE NULL,
  DtDevPrevista DATE NOT NULL,
  PRIMARY KEY(CodEmprest),
  FOREIGN KEY(Amigo_CodAmigo)
    REFERENCES Amigo(CodAmigo)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Livro_CodLivro)
    REFERENCES Livro(CodLivro)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


